[package]
name = "festival"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = 1

[dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }
rand_distr = "0.4.3"
rustc-hash = "1.1.0"

[dev-dependencies]
plotters = "0.3.4"

[build-dependencies]
cmake = "0.1.49"
